export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const SORT_USER_BY_ASC_ORDER = 'SORT_USER_BY_ASC_ORDER';
export const SORT_USER_BY_DESC_ORDER = 'SORT_USER_BY_DESC_ORDER';
